package com.yishuifengxiao.common.crawler;

import org.junit.Test;

import com.yishuifengxiao.common.crawler.extractor.content.strategy.impl.CssStrategy;
import com.yishuifengxiao.common.crawler.extractor.content.strategy.impl.CssTextStrategy;
/**
 *  css提取规则测试类
 * @author yishui
 * @date 2019年12月2日
 * @version 1.0.0
 */
public class CssExtractTest {

	private CssStrategy css = new CssStrategy();

	private CssTextStrategy ct = new CssTextStrategy();
	private static  String RULE1_PARAM1 = "p.post-meta";
	private static String RULE1_PARAM2 = "style";
	
	private static 	String RULE2_PARAM1 = "h2.post-title";
	private static String RULE2_PARAM2 = "";

	@Test
	public void testExtract() {

		String out = css.extract(HTML, RULE1_PARAM1, RULE1_PARAM2);
		System.out.println("=============================> \r\n");
		System.out.println(out);
	}
	

	@Test
	public void testCssTextStrategy() {

		String out = ct.extract(HTML, RULE2_PARAM1, RULE2_PARAM2);
		System.out.println("=============================> \r\n");
		System.out.println(out);
	}

	private final static String HTML = "<div class=\"row\">\r\n" + "        \r\n" + "\r\n" + "<!-- USE SIDEBAR -->\r\n"
			+ "    <!-- Post Container -->\r\n" + "            <div class=\"\r\n"
			+ "                col-lg-8 col-lg-offset-1\r\n" + "                col-md-8 col-md-offset-1\r\n"
			+ "                col-sm-12\r\n" + "                col-xs-12\r\n" + "                post-container\r\n"
			+ "            \">\r\n"
			+ "                <script charset=\"utf-8\" type=\"text/javascript\" src=\"https://changyan.sohu.com/upload/changyan.js\"></script>\r\n"
			+ "                <!-- Main Content -->\r\n" + "\r\n" + "\r\n" + "<div class=\"post-preview\">\r\n"
			+ "\r\n" + "    <a href=\"/2019/11/01/oauth2快速入门教程/\">\r\n" + "        <h2 class=\"post-title\">\r\n"
			+ "            oauth2快速入门教程\r\n" + "        </h2>\r\n" + "        <h3 class=\"post-subtitle\">\r\n"
			+ "            通过使用易水公共组件快速开启oauth2功能\r\n" + "        </h3>\r\n"
			+ "        <div class=\"post-content-preview\">\r\n" + "            一 快速启动\r\n" + "1 在项目中加入相关的依赖\r\n"
			+ "导入 易水公共组件 和 spring-security-oauth2-autoconfigure两个依赖\r\n"
			+ "12345678910&lt;dependency&gt;    &lt;groupId&gt;org.springframework.security.oauth.boot&lt;/groupId&gt;    &lt;artifactId&amp;g......\r\n"
			+ "        </div>\r\n" + "    </a>\r\n" + "    \r\n"
			+ "        <p class=\"post-meta\" style=\"margin: 10px 0;\">\r\n"
			+ "            Posted by yishuifengxiao on\r\n" + "            2019-11-01\r\n" + "        </p>\r\n"
			+ "        <div class=\"tags\">\r\n" + "            \r\n"
			+ "              <a href=\"/tags/#spring security\" title=\"spring security\">spring security</a>\r\n"
			+ "            \r\n" + "              <a href=\"/tags/#易水组件\" title=\"易水组件\">易水组件</a>\r\n"
			+ "            \r\n" + "        </div>\r\n" + "    \r\n" + "\r\n" + "</div>\r\n" + "<hr>\r\n" + "\r\n"
			+ "<div class=\"post-preview\">\r\n" + "\r\n" + "    <a href=\"/2019/10/31/swagger-ui快速入门教程/\">\r\n"
			+ "        <h2 class=\"post-title\">\r\n" + "            swagger ui快速入门教程\r\n" + "        </h2>\r\n"
			+ "        <h3 class=\"post-subtitle\">\r\n" + "            通过使用易水公共组件快速开启和关闭swagger ui，生成软件接口说明文档\r\n"
			+ "        </h3>\r\n" + "        <div class=\"post-content-preview\">\r\n" + "            快速启动\r\n"
			+ "1 引入相关依赖\r\n"
			+ "12345&lt;dependency&gt;    &lt;groupId&gt;com.yishuifengxiao.common&lt;/groupId&gt;    &lt;artifactId&gt;common-spring-boot-starter&lt;/artifactId&gt;    &lt;version&gt;4.1.2&lt;/vers......\r\n"
			+ "        </div>\r\n" + "    </a>\r\n" + "    \r\n"
			+ "        <p class=\"post-meta\" style=\"margin: 10px 0;\">\r\n"
			+ "            Posted by yishuifengxiao on\r\n" + "            2019-10-31\r\n" + "        </p>\r\n"
			+ "        <div class=\"tags\">\r\n" + "            \r\n"
			+ "              <a href=\"/tags/#spring security\" title=\"spring security\">spring security</a>\r\n"
			+ "            \r\n" + "              <a href=\"/tags/#易水组件\" title=\"易水组件\">易水组件</a>\r\n"
			+ "            \r\n" + "        </div>\r\n" + "    \r\n" + "\r\n" + "</div>\r\n" + "<hr>\r\n" + "\r\n"
			+ "<div class=\"post-preview\">\r\n" + "\r\n" + "    <a href=\"/2019/10/31/基于易水公共组件的全局异常捕获/\">\r\n"
			+ "        <h2 class=\"post-title\">\r\n" + "            基于易水公共组件的全局异常捕获\r\n" + "        </h2>\r\n"
			+ "        <h3 class=\"post-subtitle\">\r\n" + "            通过使用易水公共组件快速启动全局异常捕获\r\n" + "        </h3>\r\n"
			+ "        <div class=\"post-content-preview\">\r\n" + "            1 引入相关依赖\r\n"
			+ "12345&lt;dependency&gt;    &lt;groupId&gt;com.yishuifengxiao.common&lt;/groupId&gt;    &lt;artifactId&gt;common-spring-boot-starter&lt;/artifactId&gt;    &lt;version&gt;4.1.2&lt;/version&amp;g......\r\n"
			+ "        </div>\r\n" + "    </a>\r\n" + "    \r\n"
			+ "        <p class=\"post-meta\" style=\"margin: 10px 0;\">\r\n"
			+ "            Posted by yishuifengxiao on\r\n" + "            2019-10-31\r\n" + "        </p>\r\n"
			+ "        <div class=\"tags\">\r\n" + "            \r\n"
			+ "              <a href=\"/tags/#spring security\" title=\"spring security\">spring security</a>\r\n"
			+ "            \r\n" + "              <a href=\"/tags/#易水组件\" title=\"易水组件\">易水组件</a>\r\n"
			+ "            \r\n" + "        </div>\r\n" + "    \r\n" + "\r\n" + "</div>\r\n" + "<hr>\r\n" + "\r\n"
			+ "<div class=\"post-preview\">\r\n" + "\r\n" + "    <a href=\"/2019/10/31/快速搭建基于易水公共组件的权限管理系统/\">\r\n"
			+ "        <h2 class=\"post-title\">\r\n" + "            快速搭建基于易水公共组件的权限管理系统\r\n" + "        </h2>\r\n"
			+ "        <h3 class=\"post-subtitle\">\r\n" + "            通过使用易水公共组件，实现快速导入管理系统的资源，提高系统安全性，并可以进行高度定制化\r\n"
			+ "        </h3>\r\n" + "        <div class=\"post-content-preview\">\r\n" + "            快速启动\r\n"
			+ "在使用 spring security 时，可以参考以下步骤\r\n" + "\r\n" + "在项目中加入 spring security 依赖\r\n" + "\r\n"
			+ "123456789&lt;dependency&gt;	&lt;groupId&gt;org.springframework.boot&lt;/groupId&gt;	&lt;artifactId&gt;spring-boot-starter-security&lt;......\r\n"
			+ "        </div>\r\n" + "    </a>\r\n" + "    \r\n"
			+ "        <p class=\"post-meta\" style=\"margin: 10px 0;\">\r\n"
			+ "            Posted by yishuifengxiao on\r\n" + "            2019-10-31\r\n" + "        </p>\r\n"
			+ "        <div class=\"tags\">\r\n" + "            \r\n"
			+ "              <a href=\"/tags/#spring security\" title=\"spring security\">spring security</a>\r\n"
			+ "            \r\n" + "              <a href=\"/tags/#易水组件\" title=\"易水组件\">易水组件</a>\r\n"
			+ "            \r\n" + "        </div>\r\n" + "    \r\n" + "\r\n" + "</div>\r\n" + "<hr>\r\n" + "\r\n"
			+ "<div class=\"post-preview\">\r\n" + "\r\n" + "    <a href=\"/2019/10/31/基于易水公共组件的验证码快速入门教程/\">\r\n"
			+ "        <h2 class=\"post-title\">\r\n" + "            基于易水公共组件的验证码快速入门教程\r\n" + "        </h2>\r\n"
			+ "        <h3 class=\"post-subtitle\">\r\n"
			+ "            通过使用易水公共组件吗，实现快速导入图形验证码、邮件验证码和短信验证码，并可以进行高度定制化\r\n" + "        </h3>\r\n"
			+ "        <div class=\"post-content-preview\">\r\n"
			+ "            在日常开发过程中，经常需要使用到验证码功能，在易水风萧通用工具中对常见的 【图形验证码】、【邮箱验证码】、【短信验证码】做一个通用封装。在这三种类型的验证码中，目前仅对图形验证码和邮箱验证码做了缺省性实现，由于短信验证码中短信发送的特殊性，需要用户在开发过程中完成短信发送功能的具体实现。\r\n"
			+ "快速启动\r\n" + "\r\n" + "先引入相关依赖\r\n" + "\r\n" + "12345&lt;dependency&gt;    &lt;groupI......\r\n"
			+ "        </div>\r\n" + "    </a>\r\n" + "    \r\n"
			+ "        <p class=\"post-meta\" style=\"margin: 10px 0;\">\r\n"
			+ "            Posted by yishuifengxiao on\r\n" + "            2019-10-31\r\n" + "        </p>\r\n"
			+ "        <div class=\"tags\">\r\n" + "            \r\n"
			+ "              <a href=\"/tags/#spring security\" title=\"spring security\">spring security</a>\r\n"
			+ "            \r\n" + "              <a href=\"/tags/#易水组件\" title=\"易水组件\">易水组件</a>\r\n"
			+ "            \r\n" + "        </div>\r\n" + "    \r\n" + "\r\n" + "</div>\r\n" + "<hr>\r\n" + "\r\n"
			+ "<div class=\"post-preview\">\r\n" + "\r\n" + "    <a href=\"/2019/10/30/搭建基于易水公共组件的资源服务器/\">\r\n"
			+ "        <h2 class=\"post-title\">\r\n" + "            搭建基于易水公共组件的资源服务器\r\n" + "        </h2>\r\n"
			+ "        <h3 class=\"post-subtitle\">\r\n" + "            搭建基于易水公共组件的资源服务器，实现资源服务器与认证服务器相分离\r\n"
			+ "        </h3>\r\n" + "        <div class=\"post-content-preview\">\r\n"
			+ "            在使用本组件之前，需要先搭建好认证服务器，其中认证服务器可以根据业务需要进行单机或集群部署。\r\n" + "整个系统的结果如图所示\r\n" + "\r\n"
			+ "在整个系统中 ，认证服务器的作用是产生token和验证token的有效性，资源服务器是根据认证服务器的响应结果决定如何处理请求资源。\r\n" + "1 引入依赖\r\n"
			+ "完整的pom依赖文件如下\r\n" + "12345678910111213141516171819202122232425262728293......\r\n" + "        </div>\r\n"
			+ "    </a>\r\n" + "    \r\n" + "        <p class=\"post-meta\" style=\"margin: 10px 0;\">\r\n"
			+ "            Posted by yishuifengxiao on\r\n" + "            2019-10-30\r\n" + "        </p>\r\n"
			+ "        <div class=\"tags\">\r\n" + "            \r\n"
			+ "              <a href=\"/tags/#spring security\" title=\"spring security\">spring security</a>\r\n"
			+ "            \r\n" + "              <a href=\"/tags/#易水组件\" title=\"易水组件\">易水组件</a>\r\n"
			+ "            \r\n" + "        </div>\r\n" + "    \r\n" + "\r\n" + "</div>\r\n" + "<hr>\r\n" + "\r\n"
			+ "<div class=\"post-preview\">\r\n" + "\r\n" + "    <a href=\"/2019/10/25/springboot整合单点登录sso/\">\r\n"
			+ "        <h2 class=\"post-title\">\r\n" + "            springboot整合单点登录sso\r\n" + "        </h2>\r\n"
			+ "        <h3 class=\"post-subtitle\">\r\n" + "            在springboot里基于spring security实现单点登录sso\r\n"
			+ "        </h3>\r\n" + "        <div class=\"post-content-preview\">\r\n"
			+ "            如今，随着互联网技术的发展，网络用户规模越来越大，假如公司的每一个应用都建立一个用户系统，不仅极大的增加了开发的工作量，而且容易形成了信息孤岛，用户在使用公司的每个产品时都需要重复注册一次。因此许多公司为了统一管理，建立了统一认证中心，其他的应用需要通过单点登录即可获取用户信息，用户登录该公司的其他应用时也不需要在重新注册，大大节省公司用户导入成本，也提高用户使用体验。\r\n"
			+ "对于单点登录(SSO......\r\n" + "        </div>\r\n" + "    </a>\r\n" + "    \r\n"
			+ "        <p class=\"post-meta\" style=\"margin: 10px 0;\">\r\n"
			+ "            Posted by yishuifengxiao on\r\n" + "            2019-10-25\r\n" + "        </p>\r\n"
			+ "        <div class=\"tags\">\r\n" + "            \r\n"
			+ "              <a href=\"/tags/#spring security\" title=\"spring security\">spring security</a>\r\n"
			+ "            \r\n" + "              <a href=\"/tags/#易水组件\" title=\"易水组件\">易水组件</a>\r\n"
			+ "            \r\n" + "        </div>\r\n" + "    \r\n" + "\r\n" + "</div>\r\n" + "<hr>\r\n" + "\r\n"
			+ "<div class=\"post-preview\">\r\n" + "\r\n" + "    <a href=\"/2019/10/15/oauth2之token生成过程源码解读/\">\r\n"
			+ "        <h2 class=\"post-title\">\r\n" + "            oauth2之token生成过程源码解读\r\n" + "        </h2>\r\n"
			+ "        <h3 class=\"post-subtitle\">\r\n" + "            oauth2之token生成过程源码解读\r\n" + "        </h3>\r\n"
			+ "        <div class=\"post-content-preview\">\r\n"
			+ "            oauth2 中生成 token 的部分的源码在 org.springframework.security.oauth2.provider.endpoint.TokenEndpoint这个路径下，它位于\r\n"
			+ "spring-security-oauth2这个依赖包中，具体的代码如下：\r\n"
			+ "123456789101112131415161718192021222324252627282930313233......\r\n" + "        </div>\r\n"
			+ "    </a>\r\n" + "    \r\n" + "        <p class=\"post-meta\" style=\"margin: 10px 0;\">\r\n"
			+ "            Posted by yishuifengxiao on\r\n" + "            2019-10-15\r\n" + "        </p>\r\n"
			+ "        <div class=\"tags\">\r\n" + "            \r\n"
			+ "              <a href=\"/tags/#源码解读\" title=\"源码解读\">源码解读</a>\r\n" + "            \r\n"
			+ "              <a href=\"/tags/#oauth2\" title=\"oauth2\">oauth2</a>\r\n" + "            \r\n"
			+ "        </div>\r\n" + "    \r\n" + "\r\n" + "</div>\r\n" + "<hr>\r\n" + "\r\n"
			+ "<div class=\"post-preview\">\r\n" + "\r\n" + "    <a href=\"/2019/10/15/spring-security之获取当前用户信息/\">\r\n"
			+ "        <h2 class=\"post-title\">\r\n" + "            spring security之获取当前用户信息\r\n" + "        </h2>\r\n"
			+ "        <h3 class=\"post-subtitle\">\r\n" + "            spring security中获取当前用户的认证信息的几种方式\r\n"
			+ "        </h3>\r\n" + "        <div class=\"post-content-preview\">\r\n"
			+ "            1 通过 SecurityContextHolder 获取\r\n"
			+ "在SecurityContextHolder内部存储了当前与应用程序交互的主体的详细信息。 Spring Security 使用Authentication对象来表示此信息。 通常不需要自己创建Authentication对象，但是由于经常需要查询Authentication对象是相当普遍的。 可以在应用程序中的任何位置使用以下代码......\r\n"
			+ "        </div>\r\n" + "    </a>\r\n" + "    \r\n"
			+ "        <p class=\"post-meta\" style=\"margin: 10px 0;\">\r\n"
			+ "            Posted by yishuifengxiao on\r\n" + "            2019-10-15\r\n" + "        </p>\r\n"
			+ "        <div class=\"tags\">\r\n" + "            \r\n"
			+ "              <a href=\"/tags/#spring security\" title=\"spring security\">spring security</a>\r\n"
			+ "            \r\n" + "        </div>\r\n" + "    \r\n" + "\r\n" + "</div>\r\n" + "<hr>\r\n" + "\r\n"
			+ "<div class=\"post-preview\">\r\n" + "\r\n" + "    <a href=\"/2019/09/24/logstash基础入门教程/\">\r\n"
			+ "        <h2 class=\"post-title\">\r\n" + "            logstash基础入门教程\r\n" + "        </h2>\r\n"
			+ "        <h3 class=\"post-subtitle\">\r\n" + "            logstash基础入门教程\r\n" + "        </h3>\r\n"
			+ "        <div class=\"post-content-preview\">\r\n" + "            一 常用命令\r\n" + "1.1 常用命令\r\n" + "\r\n"
			+ "–node.name\r\n" + "-f --path.conf pipeline 路径，可以是文件或文件夹\r\n"
			+ "–path.settings logstash 配置文件夹路径，其中要包含logstash.yml\r\n" + "-e config.string 指明 pipeline 内容，多用于测试\r\n"
			+ "-w pipeline.workers\r\n" + "-b pipeline.batch.size\r\n" + "–......\r\n" + "        </div>\r\n"
			+ "    </a>\r\n" + "    \r\n" + "        <p class=\"post-meta\" style=\"margin: 10px 0;\">\r\n"
			+ "            Posted by yishuifengxiao on\r\n" + "            2019-09-24\r\n" + "        </p>\r\n"
			+ "        <div class=\"tags\">\r\n" + "            \r\n"
			+ "              <a href=\"/tags/#入门教程\" title=\"入门教程\">入门教程</a>\r\n" + "            \r\n"
			+ "              <a href=\"/tags/#ElasticStack\" title=\"ElasticStack\">ElasticStack</a>\r\n"
			+ "            \r\n" + "              <a href=\"/tags/#logstash\" title=\"logstash\">logstash</a>\r\n"
			+ "            \r\n" + "        </div>\r\n" + "    \r\n" + "\r\n" + "</div>\r\n" + "<hr>\r\n" + "\r\n"
			+ "\r\n" + "\r\n" + "<!-- Pager -->\r\n" + "\r\n" + "<ul class=\"pager\">\r\n" + "    \r\n" + "    \r\n"
			+ "        <li class=\"next\">\r\n" + "            <a href=\"/archives/2/\">Older Posts →</a>\r\n"
			+ "        </li>\r\n" + "    \r\n" + "</ul>\r\n" + "\r\n" + "\r\n" + "\r\n"
			+ "                <!-- 如果开启评论功能 -->\r\n" + "                \r\n" + "            </div>\r\n" + "\r\n"
			+ "          <!-- Sidebar Container -->\r\n" + "<div class=\"\r\n" + "    col-lg-3 col-lg-offset-0\r\n"
			+ "    col-md-3 col-md-offset-0\r\n" + "    col-sm-12\r\n" + "    col-xs-12\r\n"
			+ "    sidebar-container\r\n" + "\">\r\n" + "    \r\n" + "        <!-- Featured Tags -->\r\n" + "\r\n"
			+ "<section>\r\n" + "    <!-- no hr -->\r\n" + "    <h5><a href=\"/tags/\">FEATURED TAGS</a></h5>\r\n"
			+ "    <div class=\"tags\">\r\n" + "        \r\n" + "            \r\n"
			+ "            <a href=\"/tags/#性能测试\" title=\"性能测试\" rel=\"9\">性能测试</a>\r\n" + "            \r\n"
			+ "        \r\n" + "            \r\n"
			+ "            <a href=\"/tags/#linux\" title=\"linux\" rel=\"2\">linux</a>\r\n" + "            \r\n"
			+ "        \r\n" + "            \r\n"
			+ "            <a href=\"/tags/#node.js\" title=\"node.js\" rel=\"3\">node.js</a>\r\n" + "            \r\n"
			+ "        \r\n" + "            \r\n"
			+ "            <a href=\"/tags/#入门教程\" title=\"入门教程\" rel=\"13\">入门教程</a>\r\n" + "            \r\n"
			+ "        \r\n" + "            \r\n"
			+ "            <a href=\"/tags/#前端\" title=\"前端\" rel=\"4\">前端</a>\r\n" + "            \r\n"
			+ "        \r\n" + "            \r\n"
			+ "            <a href=\"/tags/#java\" title=\"java\" rel=\"6\">java</a>\r\n" + "            \r\n"
			+ "        \r\n" + "            \r\n" + "        \r\n" + "            \r\n"
			+ "            <a href=\"/tags/#jmeter\" title=\"jmeter\" rel=\"6\">jmeter</a>\r\n" + "            \r\n"
			+ "        \r\n" + "            \r\n" + "        \r\n" + "            \r\n" + "        \r\n"
			+ "            \r\n" + "        \r\n" + "            \r\n"
			+ "            <a href=\"/tags/#docker\" title=\"docker\" rel=\"5\">docker</a>\r\n" + "            \r\n"
			+ "        \r\n" + "            \r\n" + "        \r\n" + "            \r\n" + "        \r\n"
			+ "            \r\n" + "        \r\n" + "            \r\n"
			+ "            <a href=\"/tags/#ElasticStack\" title=\"ElasticStack\" rel=\"2\">ElasticStack</a>\r\n"
			+ "            \r\n" + "        \r\n" + "            \r\n" + "        \r\n" + "            \r\n"
			+ "        \r\n" + "            \r\n" + "        \r\n" + "            \r\n" + "        \r\n"
			+ "            \r\n" + "        \r\n" + "            \r\n"
			+ "            <a href=\"/tags/#spring security\" title=\"spring security\" rel=\"8\">spring security</a>\r\n"
			+ "            \r\n" + "        \r\n" + "            \r\n"
			+ "            <a href=\"/tags/#易水组件\" title=\"易水组件\" rel=\"9\">易水组件</a>\r\n" + "            \r\n"
			+ "        \r\n" + "            \r\n" + "        \r\n" + "            \r\n"
			+ "            <a href=\"/tags/#spring cloud\" title=\"spring cloud\" rel=\"4\">spring cloud</a>\r\n"
			+ "            \r\n" + "        \r\n" + "            \r\n"
			+ "            <a href=\"/tags/#微服务\" title=\"微服务\" rel=\"4\">微服务</a>\r\n" + "            \r\n"
			+ "        \r\n" + "            \r\n"
			+ "            <a href=\"/tags/#随笔\" title=\"随笔\" rel=\"15\">随笔</a>\r\n" + "            \r\n"
			+ "        \r\n" + "            \r\n" + "        \r\n" + "    </div>\r\n" + "</section>\r\n" + "\r\n"
			+ "        <hr>\r\n" + "    \r\n" + "        <!-- Short About -->\r\n"
			+ "<section class=\"visible-md visible-lg\">\r\n" + "    <h5><a href=\"/about/\">ABOUT ME</a></h5>\r\n"
			+ "    <div class=\"short-about\">\r\n" + "\r\n" + "        \r\n"
			+ "            <img id=\"avatar_pic\" src=\"/img/ironman-draw.png\">\r\n" + "        \r\n" + "\r\n"
			+ "        \r\n" + "            <p>关注我的微信，互相交流</p>\r\n" + "        \r\n" + "\r\n"
			+ "        <!-- SNS Link -->\r\n" + "        <ul class=\"list-inline\">\r\n" + "            \r\n"
			+ "            \r\n" + "            \r\n" + "\r\n" + "            \r\n" + "                <li>\r\n"
			+ "                    <a target=\"_blank\" href=\"http://weibo.com/yishuifengxiao\">\r\n"
			+ "                        <span class=\"fa-stack fa-lg\">\r\n"
			+ "                            <i class=\"fa fa-circle fa-stack-2x\"></i>\r\n"
			+ "                            <i class=\"fa fa-weibo fa-stack-1x fa-inverse\"></i>\r\n"
			+ "                        </span>\r\n" + "                    </a>\r\n" + "                </li>\r\n"
			+ "            \r\n" + "\r\n" + "            \r\n" + "                <li>\r\n"
			+ "                    <a target=\"_blank\" href=\"https://www.facebook.com/yishuifengxiao\">\r\n"
			+ "                        <span class=\"fa-stack fa-lg\">\r\n"
			+ "                            <i class=\"fa fa-circle fa-stack-2x\"></i>\r\n"
			+ "                            <i class=\"fa fa-facebook fa-stack-1x fa-inverse\"></i>\r\n"
			+ "                        </span>\r\n" + "                    </a>\r\n" + "                </li>\r\n"
			+ "            \r\n" + "\r\n" + "            \r\n" + "                <li>\r\n"
			+ "                    <a target=\"_blank\" href=\"https://github.com/yishuifengxiao\">\r\n"
			+ "                        <span class=\"fa-stack fa-lg\">\r\n"
			+ "                            <i class=\"fa fa-circle fa-stack-2x\"></i>\r\n"
			+ "                            <i class=\"fa fa-github fa-stack-1x fa-inverse\"></i>\r\n"
			+ "                        </span>\r\n" + "                    </a>\r\n" + "                </li>\r\n"
			+ "            \r\n" + "            \r\n" + "            \r\n" + "            \r\n" + "        </ul>\r\n"
			+ "    </div>\r\n" + "</section>\r\n" + "        <hr>\r\n" + "    \r\n" + "        \r\n"
			+ "  <h5>RECENT POSTS\r\n" + "  <div class=\"widget\">\r\n" + "    <ul class=\"recent\">\r\n" + "      \r\n"
			+ "        <li>\r\n" + "          <a href=\"/2019/11/01/oauth2快速入门教程/\">oauth2快速入门教程</a>\r\n"
			+ "        </li>\r\n" + "      \r\n" + "        <li>\r\n"
			+ "          <a href=\"/2019/10/31/swagger-ui快速入门教程/\">swagger ui快速入门教程</a>\r\n" + "        </li>\r\n"
			+ "      \r\n" + "        <li>\r\n"
			+ "          <a href=\"/2019/10/31/基于易水公共组件的全局异常捕获/\">基于易水公共组件的全局异常捕获</a>\r\n" + "        </li>\r\n"
			+ "      \r\n" + "        <li>\r\n"
			+ "          <a href=\"/2019/10/31/快速搭建基于易水公共组件的权限管理系统/\">快速搭建基于易水公共组件的权限管理系统</a>\r\n" + "        </li>\r\n"
			+ "      \r\n" + "        <li>\r\n"
			+ "          <a href=\"/2019/10/31/基于易水公共组件的验证码快速入门教程/\">基于易水公共组件的验证码快速入门教程</a>\r\n" + "        </li>\r\n"
			+ "      \r\n" + "    </ul>\r\n" + "  </div>\r\n" + "</h5>\r\n" + "        <hr>\r\n" + "    \r\n"
			+ "        <!-- Friends Blog -->\r\n" + "\r\n" + "<h5>FRIENDS</h5>\r\n" + "<ul class=\"list-inline\">\r\n"
			+ "\r\n" + "    \r\n" + "        <li><a href=\"https://www.csdn.net/\" target=\"_blank\">CSDN</a></li>\r\n"
			+ "    \r\n" + "        <li><a href=\"http://www.runoob.com/\" target=\"_blank\">W3C菜鸟</a></li>\r\n"
			+ "    \r\n"
			+ "        <li><a href=\"https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#getting-started-installing-the-cli\" target=\"_blank\">spring boot</a></li>\r\n"
			+ "    \r\n"
			+ "        <li><a href=\"https://cloud.spring.io/spring-cloud-static/Finchley.SR2/single/spring-cloud.html#spring-cloud-eureka-server\" target=\"_blank\">spring cloud</a></li>\r\n"
			+ "    \r\n"
			+ "        <li><a href=\"https://docs.spring.io/spring-security/site/docs/5.1.2.RELEASE/reference/htmlsingle/#jc-method\" target=\"_blank\">spring security</a></li>\r\n"
			+ "    \r\n"
			+ "        <li><a href=\"https://docs.spring.io/spring/docs/4.3.14.BUILD-SNAPSHOT/spring-framework-reference/htmlsingle/\" target=\"_blank\">spring</a></li>\r\n"
			+ "    \r\n" + "        <li><a href=\"https://gitee.com/zhiyubujian\" target=\"_blank\">码云</a></li>\r\n"
			+ "    \r\n" + "</ul>\r\n" + "\r\n" + "        <hr>\r\n" + "    \r\n" + "</div>\r\n" + "\r\n"
			+ "        \r\n" + "    </div>";

}
